### ISSUE TITLE
Directly assigning an object to a Group is not implemented

### ISSUE THREAD

**Issue by stringfellow** [vittoriozamboni/django-groups-manager#2]
Is this intentionally left unimplemented in order to implement in a subclass?

I'd like to be able to do (as the API shows) e.g.

```
my_group.assign_object(some_object)
```

instead of having to associate that with a user (which the docs show) e.g.

```
my_user.assign_object(my_group, some_object)
```

**Comment by vittoriozamboni** [comment]
Hi stringfellow, thank you for report your needs. The feature you wish to use was in a TODO status. I have updated the application with direct assign of objects to groups (and Django 1.9 support). You can use it with version 0.3.0+.

**Comment by stringfellow** [comment]
Wow! Thanks man! Super fast :zap:
