### ISSUE TITLE
Is possible implement django-moderation with groups manager?

### ISSUE THREAD

**Issue by Allan-Nava** [vittoriozamboni/django-groups-manager#22]
Hi @OskarPersson,

is possible? 

Thanks

**Comment by Allan-Nava** [comment]
Any news?

**Comment by vittoriozamboni** [comment]
@Allan-Nava I don't know how django-moderation works and unfortunately I don't have resources to investigate. It seems it can work on any valid object, are you having issues related to groups manager?

**Comment by Allan-Nava** [comment]
I used the django guardian, thanks for support
