### ISSUE TITLE
Runtime Error when installing with Docker Compose

### ISSUE THREAD

**Issue by cloudeeo** [vittoriozamboni/django-groups-manager#35]
I am trying to use this app with a Django deployment under Docker compose (DB + web app). 
After installing  the app I get this error message

RuntimeError: Model class guardian.models.UserObjectPermission doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

The app is installed and listed in INSTALLED_APPS, what am I missing?

thank you!
Claudio

**Comment by cloudeeo** [comment]
Actually I found the problem. You need to add "guardian" to INSTALLED_APPS.

**Comment by mazulo** [comment]
I got the exact same error and figured this out. I think it should be added to the docs

**Comment by vittoriozamboni** [comment]
Hi! Thank you for the contributon an sorry for the delay. 
I will add it to the documentation.
