### ISSUE TITLE
Migrations warning

### ISSUE THREAD

**Issue by Turbid** [vittoriozamboni/django-groups-manager#4]
I have this warning at makemigrations:

System check identified some issues:

> WARNINGS:
> groups_manager.Group.group_entities: (fields.W340) null has no effect on ManyToManyField.
> groups_manager.GroupMember.roles: (fields.W340) null has no effect on ManyToManyField.
> No changes detected

Python 3.5.2
Django 1.9.7
django-groups-manager 0.4.1

**Comment by gofullthrottle** [comment]
Can this be solved by removing null=TRUE to the group_entities M2M (line 249) and the roles null=TRUE on line 504?

**Comment by vittoriozamboni** [comment]
Hi! 
Thank you for posting this warning and. Gofullthrottle is right, I will fix this soon.

**Comment by vittoriozamboni** [comment]
The fix has been applied to version 0.4.2
