### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonfield'

### ISSUE THREAD

**Issue by divick** [vittoriozamboni/django-groups-manager#41]
The moment I add groups_manger to INSTALLED_APPS, I get this exception. I think we can simply use JSONField which is now natively supported in Django which is now supported by both postgres as well as MySQL.

**Comment by vittoriozamboni** [comment]
Hi @divick , thank you for your comment.

I can't find in the documentation a place where it says it is supported by MySQL without 3rd party elements.
I can make it configurable from the settings, so you can pass the JSONField wrapper you prefer in case of MySQL for example.

**Comment by io-ma** [comment]
Same here, I am using Postgres though.
I added `from django.contrib.postgres.fields import JSONField` in the models.py
Of course I needed to do some surgery on the migration files too.
I also had to replace `default={}` with `default=dict` - there was an error about it
Now I get a `TypeError: __init__() got an unexpected keyword argument 'load_kwargs'` in the 0006 migration file...
L.E.:
Digging further, I noticed they deprecated jsonfield2 (saw you have it in requirements)
They merged it back into jsonfield at the beginning of March.
ARCHIVE NOTICE: This package has been deprecated and merged back into jsonfield.
https://pypi.org/project/jsonfield2/
This:
https://github.com/rpkilby/jsonfield
I'll try to install it , see if it works ;-)
YAY! It works!!!!
So, just replace jsonfield2 with jsonfield v 3.1.0 and you should be good!
Opened a tiny PR

**Comment by vittoriozamboni** [comment]
Thanks for your investigation and the PR. 
I left a comment in there about the `tox.ini` file.

**Comment by io-ma** [comment]
Ok, it's done. Changed it and removed that line too. I opened a new PR

**Comment by JamesWilmot** [comment]
Hi @vittoriozamboni,

Just wondering if this could be packaged up into a release and pushed to pypi?

Thanks for this useful django app.

**Comment by vittoriozamboni** [comment]
Hi, apologies to all, I thought I did!

The new version 1.0.2 includes this change.
