### ISSUE TITLE
standard templates, from groups_manager’s urls

### ISSUE THREAD

**Issue by ibnubay** [vittoriozamboni/django-groups-manager#5]
can u preview or tell step by step when to use standard templates, from groups_manager’s urls?
i already run it, but i still confuse to use it...

I already change it to be working for django 1.9.
.... working (change to bootstrap 3.3.7)

**Comment by vittoriozamboni** [comment]
The URLs and Templates will be refactored, but the templates will not be officially supported. 
The templates schema is as follow: 
- groups_manager.html extends base.html ;
- generic model page (like member.html) extends groups_manager.html;
- specific model page (like member_detail.html) extends generic model page.

The following blocks are considered:
- sidebar  
- breadcrumbs (requires a <ul></ul> outside the first one, i.e. in base.html)
- content

An example can be found in testproject template folder (it has outdated packages but the schema is the same). 
Visually, you can imagine something like this: https://plnkr.co/edit/zHqDYlHpTIPteD6JLocy?p=preview
