### ISSUE TITLE
Member and Django User

### ISSUE THREAD

**Issue by dpineiden** [vittoriozamboni/django-groups-manager#53]
Hi again!

I think the Member class could has a relationship with django user OneToOne, in that way the reverse call is direct.

Like 'user.member' despite 'user.members.first()' (because uses foreignkey'.

Is a bit more consistent because identifies one member with one user....

could help

**Comment by vittoriozamboni** [comment]
Hi!

No it's not the same, a single user can be member of more than one group which might have different settings.
