### ISSUE TITLE
Use python-slugify instead of awesome-slugify

### ISSUE THREAD

**Issue by BoPeng** [vittoriozamboni/django-groups-manager#54]
`django-groups-manager` is released under a MIT license. It requires `awesome-slugify`, which is released under GPLv3. Is it true that this effectively revokes the MIT license of `django-groups-manager`?

I tried to use `python-slugify` but `to_lower` is not an acceptable option to its `slugify` function and triggers an error due to 

https://github.com/vittoriozamboni/django-groups-manager/blob/d02361e6f2825c174410db676ec3fb28c54e0256/groups_manager/models.py#L220

**Comment by vittoriozamboni** [comment]
Hi! 

Thank you for pointing this out.
At this point I am going to remove entirely the need for the slugify function and add a setting to customize it and remove `awesome-slugify` from the direct dependencies.
I'll add an example to the documentation.

The two packages works differently and in my current projects I still need `awesome-slugify`, and I don't want to install a dependency I am not going to use.

**Comment by BoPeng** [comment]
Actually if no fancy feature is required, 

```
from django.utils.text import slugify
```
would also work and there is no need for any dependency.

**Comment by vittoriozamboni** [comment]
Thank you @BoPeng , a new version (1.1.0) will be released soon with Django's slugify by default and two settings to customize it.
