### ISSUE TITLE
Broken with Django 4.0

### ISSUE THREAD

**Issue by Gornoka** [vittoriozamboni/django-groups-manager#59]
Currently this does not work with Django 4.0 as far as I could see the only problem is the usage of the deprecated alias 

````python3
django.conf.urls.url
````
I would propose a quick fix later, however it should be discussed whether the old behaviour of using the alias is still kept for backwards compatibility or not.

**Comment by Gornoka** [comment]
Context regarding the deprecated function:
https://docs.djangoproject.com/en/1.8/ref/urls/#url
https://docs.djangoproject.com/en/2.0/ref/urls/#url
The function is already deprecated since 1.8 and has been an alias for `re_path` since 2.0 I would consider removing it entirely, the current pr #60 still keeps it as a backup in case of an ``ImportError``.

**Comment by vittoriozamboni** [comment]
Hi @Gornoka , 
thank you for flagging the issue and providing a PR to fix it, maintaining the old functionality as well.
I will merge it and fix the test project as well, so the tests can pass. I will release a new version after it.
