### ISSUE TITLE
Reason of adding prefix and suffix of original django auth.models

### ISSUE THREAD

**Issue by sssuperman** [vittoriozamboni/django-groups-manager#6]
Hi.
I am trying to introduce django groups manager to my django site but I found there are some behavior when syncing with main django auth models. It will add some suffix and prefix to original model. I am planing to re-design this behavior. Could you tell why you need to add prefix and suffix ?

Chang

**Comment by vittoriozamboni** [comment]
Hi Chang, 
if you need to keep the django names clean, you can tweak suffixes and prefixes as empty. The settings options (http://django-groups-manager.readthedocs.io/en/latest/settings.html) allows you to manage how these values are used, i.e. on your django settings file add:

``` python
GROUPS_MANAGER = {
    # User and Groups sync settings
    'GROUP_NAME_PREFIX': "",
    'GROUP_NAME_SUFFIX': "",
    'USER_USERNAME_PREFIX': "",
    'USER_USERNAME_SUFFIX': "",
}
```

Prefixes and suffixes are required when you need to create new models based on groups manager and you don't want them to conflict. For example, if you create two models named "HighSchool" (for a list of high schools) and "College" (for a list of colleges), and you add the same instance name in both models, the group name will result the same. To avoid this, a random number will prevent to have the same name.

**Comment by guyschlider** [comment]
Hey @vittoriozamboni - sorry for bumping this old issue, but we couldn't really understand here why would we want to **MODIFY usernames** of existing usernames in our Django Auth User model?

We suddenly found out while trying to use this awesome library that existing usernames suddenly changed. 
What was the original thought that lead to this feature?

**Comment by vittoriozamboni** [comment]
Hi @guyschlider, thank you for your kind words!
The prefix/suffix feature allows to avoid conflicts when users are created automatically based only on names (I. E. Two different "Guy S" would result in the same username) but also to distinguish between "real" users of the application and "meta" users. If you write all your application probably you don't need this feature, but sometimes you need to integrate with 3rd party libraries which requires a user instance to be linked,and you can't separate real users (User model) with meta users (Member model).
