### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonfield'  error when running "python manage.py syncdb or migrate"

### ISSUE THREAD

**Issue by dw-liedji** [vittoriozamboni/django-groups-manager#62]
I have configure the library as indicated in the documentation. But having the following error:

_ModuleNotFoundError: No module named 'jsonfield'_

He are my settings:

- configurations:

```Python
INSTALLED_APPS += (
    'guardian',  # installed 
    'groups_manager', # also installed
)
```

- Django version: 4.1

**Comment by vittoriozamboni** [comment]
Hi @dw-liedji , you need to install `jsonfield` as well (`pip install jsonfield`).

**Comment by dw-liedji** [comment]
Hi @vittoriozamboni , thank your for your anwer. It is now working. However, I think this should by mentioned in the documentation.

**Comment by vittoriozamboni** [comment]
Hi @dw-liedji, glad it's working.
It is actually in the Requirements block (the last row).
