### ISSUE TITLE
ImportError: No module named django_helper_forms.forms

### ISSUE THREAD

**Issue by rajaramsrn** [vittoriozamboni/django-groups-manager#9]
Installing the groups manager 0.5.0 wth pip install does not also pull the django_helper_forms dependency resulting in following crash while adding in urls. No explicit mention in the docs to install as such as well.

    url(r'^groups-manager/', include('groups_manager.urls', namespace='groups_manager')),

  _File "/Users/rs/projects/lipton/lib/python2.7/site-packages/groups_manager/urls.py", line 3, in <module>
    from groups_manager import views
  File "/Users/rs/projects/lipton/lib/python2.7/site-packages/groups_manager/views.py", line 9, in <module>
    from groups_manager import models, forms, settings
  File "/Users/rs/projects/lipton/lib/python2.7/site-packages/groups_manager/forms.py", line 3, in <module>
    from django_helper_forms.forms import DictionaryFieldsForm
ImportError: No module named django_helper_forms.forms_

**Comment by vittoriozamboni** [comment]
Hi rajaramsrn, 
thank you for the feedback. I will fix it as soon as possible.

**Comment by vittoriozamboni** [comment]
The issue has been resolved in version 0.5.1, that is now available.

**Comment by rajaramsrn** [comment]
Thank you!
